- name : install nfs-kernel-server package
  apt:
    name: nfs-kernel-server
    state: latest
    update_cache: yes

- name: set sysctl rmem and wmem settings
  sysctl:
    name: "{{ item }}"
    value: 219136
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.core.rmem_default
    - net.core.rmem_max
    - net.core.wmem_default
    - net.core.wmem_max

- name: increase number of nfs server threads
  lineinfile:
    path: /etc/default/nfs-kernel-server
    state: present
    regexp: '^RPCNFSDCOUNT=.*$'
    line: 'RPCNFSDCOUNT=32'
  notify: restart nfs-kernel-server

- name: create export directories
  file:
    state: directory
    path: "{{ item.value.nfs_export }}"
    mode: 0755
  with_dict: "{{ nfs_exports }}"

- name: add exports
  template:
    src: exports
    dest: /etc/exports
  notify: reload exports

- name: configure user id mappping
  copy:
    src: idmapd.conf
    dest: /etc/idmapd.conf
  notify: restart nfs-kernel-server
