- name: Add /etc/hosts entry for NFS server
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{nfs_server_ip}} {{nfs_server_domain_name}}"

- name: install nfs-common package
  apt:
    name: nfs-common
    state: latest
    update_cache: yes

- name: Ensure rpcbind is running
  service:
    name: rpcbind
    state: started
    enabled: yes

- name: Ensure mount directories exist
  file:
    path: "{{nfs_data_mount_root}}/{{item.key}}"
    state: directory
  with_dict: "{{ nfs_exports }}"

# Do not need fstab as mount options are handled via autofs and ldap
#- name: configure /etc/fstab on clients
#  mount:
#    name: "{{nfs_data_mount_root}}/{{item.key}}"
#    src: "{{nfs_server_ip}}:{{item.value.nfs_export}}"
#    fstype: nfs
#    opts: "{{item.value.mount_opts}}"
#    state: mounted
#  with_dict: "{{ nfs_exports }}"